// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: whatsapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is a generic void message used when no input parameters are required.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{0}
}

// MessageEvent represents an incoming message received from WhatsApp.
type MessageEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JID of the sender.
	// Required. Example: "1234567890@s.whatsapp.net"
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// The JID of the receiver (usually the bot's JID).
	// Required. Example: "0987654321@s.whatsapp.net"
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// The pushname or display name of the sender.
	// Optional. Example: "John Doe"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The text content of the message or the media caption.
	// Optional (if media is present). Example: "Hello, world!"
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// The time the message was received in ISO 8601 or RFC3339 format.
	// Required. Example: "2023-10-27T10:00:00Z"
	Timestamp string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The raw bytes of the media file (image, document, etc.).
	// Optional. Example: [0x89, 0x50, 0x4E, 0x47, ...]
	Binary []byte `protobuf:"bytes,6,opt,name=binary,proto3" json:"binary,omitempty"`
	// The name of the file if binary data is present.
	// Optional. Example: "photo.jpg"
	Filename      string `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *MessageEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageEvent) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MessageEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MessageEvent) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *MessageEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// QRCodeResponse handles the states of the QR login process.
type QRCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The QR code string intended to be displayed or converted to an image.
	// Optional (present only if status is "code"). Example: "2@...==,..."
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// The current status of the login flow.
	// Required. Example: "code", "timeout", "success", "error"
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCodeResponse) Reset() {
	*x = QRCodeResponse{}
	mi := &file_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeResponse) ProtoMessage() {}

func (x *QRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeResponse.ProtoReflect.Descriptor instead.
func (*QRCodeResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *QRCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QRCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SendRequest contains the necessary data to send a message.
type SendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The destination phone number or JID.
	// Required. Example: "1234567890" or "1234567890@s.whatsapp.net"
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// The text body or caption for media.
	// Optional (if binary is provided). Example: "Here is your invoice."
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// The specific device JID to send from. If empty, the server picks the first available connected device.
	// Optional. Example: "9876543210@s.whatsapp.net"
	FromJid string `protobuf:"bytes,3,opt,name=from_jid,json=fromJid,proto3" json:"from_jid,omitempty"`
	// The raw file data to upload and send.
	// Optional. Example: [bytes...]
	Binary []byte `protobuf:"bytes,4,opt,name=binary,proto3" json:"binary,omitempty"`
	// The filename (extension determines MIME type).
	// Optional (Required if binary is present). Example: "invoice.pdf"
	Filename      string `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *SendRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendRequest) GetFromJid() string {
	if x != nil {
		return x.FromJid
	}
	return ""
}

func (x *SendRequest) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *SendRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// SendResponse indicates the result of a message sending attempt.
type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the message was successfully handed off to the WhatsApp servers.
	// Required. Example: true
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error description if success is false.
	// Optional. Example: "server disconnected"
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *SendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DeviceInfo holds summary data for a single WhatsApp session.
type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full JID of the device, often appended with status text by the server.
	// Required. Example: "1234567890@s.whatsapp.net (connected)"
	Jid           string `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceInfo) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

// DeviceList wraps a list of devices.
type DeviceList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of known devices.
	// Optional (can be empty).
	Devices       []*DeviceInfo `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_whatsapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceList) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DeviceID identifies a specific session for administrative actions.
type DeviceID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JID (or partial JID) of the device to target.
	// Required. Example: "1234567890"
	Jid           string `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceID) Reset() {
	*x = DeviceID{}
	mi := &file_whatsapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceID) ProtoMessage() {}

func (x *DeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceID.ProtoReflect.Descriptor instead.
func (*DeviceID) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceID) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

// StatusResponse is a generic acknowledgment for void-return operations.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation completed successfully.
	// Required. Example: true
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if operation failed.
	// Optional. Example: "Device not found"
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_whatsapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The phone number of the device to link (e.g., "34600111222")
	PhoneNumber   string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_whatsapp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

var File_whatsapp_proto protoreflect.FileDescriptor

const file_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x0ewhatsapp.proto\x12\bwhatsapp\"\a\n" +
	"\x05Empty\"\xac\x01\n" +
	"\fMessageEvent\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06binary\x18\x06 \x01(\fR\x06binary\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\"<\n" +
	"\x0eQRCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x80\x01\n" +
	"\vSendRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bfrom_jid\x18\x03 \x01(\tR\afromJid\x12\x16\n" +
	"\x06binary\x18\x04 \x01(\fR\x06binary\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\">\n" +
	"\fSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1e\n" +
	"\n" +
	"DeviceInfo\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"<\n" +
	"\n" +
	"DeviceList\x12.\n" +
	"\adevices\x18\x01 \x03(\v2\x14.whatsapp.DeviceInfoR\adevices\"\x1c\n" +
	"\bDeviceID\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"@\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\fLoginRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber2\xfe\x02\n" +
	"\x0fWhatsAppService\x12;\n" +
	"\x0eStreamMessages\x12\x0f.whatsapp.Empty\x1a\x16.whatsapp.MessageEvent0\x01\x12>\n" +
	"\n" +
	"StartLogin\x12\x16.whatsapp.LoginRequest\x1a\x18.whatsapp.QRCodeResponse\x12<\n" +
	"\vSendMessage\x12\x15.whatsapp.SendRequest\x1a\x16.whatsapp.SendResponse\x124\n" +
	"\vListDevices\x12\x0f.whatsapp.Empty\x1a\x14.whatsapp.DeviceList\x12<\n" +
	"\fLogoutDevice\x12\x12.whatsapp.DeviceID\x1a\x18.whatsapp.StatusResponse\x12<\n" +
	"\fDeleteDevice\x12\x12.whatsapp.DeviceID\x1a\x18.whatsapp.StatusResponseB\tZ\a./protob\x06proto3"

var (
	file_whatsapp_proto_rawDescOnce sync.Once
	file_whatsapp_proto_rawDescData []byte
)

func file_whatsapp_proto_rawDescGZIP() []byte {
	file_whatsapp_proto_rawDescOnce.Do(func() {
		file_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whatsapp_proto_rawDesc), len(file_whatsapp_proto_rawDesc)))
	})
	return file_whatsapp_proto_rawDescData
}

var file_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_whatsapp_proto_goTypes = []any{
	(*Empty)(nil),          // 0: whatsapp.Empty
	(*MessageEvent)(nil),   // 1: whatsapp.MessageEvent
	(*QRCodeResponse)(nil), // 2: whatsapp.QRCodeResponse
	(*SendRequest)(nil),    // 3: whatsapp.SendRequest
	(*SendResponse)(nil),   // 4: whatsapp.SendResponse
	(*DeviceInfo)(nil),     // 5: whatsapp.DeviceInfo
	(*DeviceList)(nil),     // 6: whatsapp.DeviceList
	(*DeviceID)(nil),       // 7: whatsapp.DeviceID
	(*StatusResponse)(nil), // 8: whatsapp.StatusResponse
	(*LoginRequest)(nil),   // 9: whatsapp.LoginRequest
}
var file_whatsapp_proto_depIdxs = []int32{
	5, // 0: whatsapp.DeviceList.devices:type_name -> whatsapp.DeviceInfo
	0, // 1: whatsapp.WhatsAppService.StreamMessages:input_type -> whatsapp.Empty
	9, // 2: whatsapp.WhatsAppService.StartLogin:input_type -> whatsapp.LoginRequest
	3, // 3: whatsapp.WhatsAppService.SendMessage:input_type -> whatsapp.SendRequest
	0, // 4: whatsapp.WhatsAppService.ListDevices:input_type -> whatsapp.Empty
	7, // 5: whatsapp.WhatsAppService.LogoutDevice:input_type -> whatsapp.DeviceID
	7, // 6: whatsapp.WhatsAppService.DeleteDevice:input_type -> whatsapp.DeviceID
	1, // 7: whatsapp.WhatsAppService.StreamMessages:output_type -> whatsapp.MessageEvent
	2, // 8: whatsapp.WhatsAppService.StartLogin:output_type -> whatsapp.QRCodeResponse
	4, // 9: whatsapp.WhatsAppService.SendMessage:output_type -> whatsapp.SendResponse
	6, // 10: whatsapp.WhatsAppService.ListDevices:output_type -> whatsapp.DeviceList
	8, // 11: whatsapp.WhatsAppService.LogoutDevice:output_type -> whatsapp.StatusResponse
	8, // 12: whatsapp.WhatsAppService.DeleteDevice:output_type -> whatsapp.StatusResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_whatsapp_proto_init() }
func file_whatsapp_proto_init() {
	if File_whatsapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatsapp_proto_rawDesc), len(file_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whatsapp_proto_goTypes,
		DependencyIndexes: file_whatsapp_proto_depIdxs,
		MessageInfos:      file_whatsapp_proto_msgTypes,
	}.Build()
	File_whatsapp_proto = out.File
	file_whatsapp_proto_goTypes = nil
	file_whatsapp_proto_depIdxs = nil
}
